-- 4. Motifique o arquivo arvore.hs (disponı́vel no Moodle) de forma a adicionar novas operações a nossa
-- árvore:
-- A: Crie uma função com a seguinte assinatura: ocorrenciasElemento :: Arvore -> Int -> Int, a
-- qual recebe um número e deve retornar a quantidade de ocorrências dele na árvore.
-- B: Crie uma função com a seguinte assinatura: maioresQueElemento :: Arvore -> Int -> Int, a
-- qual recebe um número e deve retornar a quantidade de números maiores que ele na árvore.
-- C: Crie uma função com a seguinte assinatura: mediaElementos :: Arvore -> Float, a qual deve
-- retornar a média dos números na árvore. DICA: utilize a função fromIntegral para converter um
-- tipo inteiro para um tipo compatı́vel com o operador de divisão /
-- D: Crie uma função com a seguinte assinatura: quantidade ::
-- a quantidade de elementos na árvore.Arvore -> Int, a qual deve retornar
-- E: Crie uma função com a seguinte assinatura: elementos ::
-- uma lista com todos os elementos na árvore.